### ISSUE TITLE
关于data模块的问题

### ISSUE THREAD

**Issue by ZiqiChing** [houking-can/CCKS2019-Task5#2]
你好，我在跑这个代码的时候遇到了一个问题，报错为 ImportError: cannot import name 'pad_sequences' from 'data' (P:\Anaconda3\lib\site-packages\data\__init__.py) 是不是我的data版本问题呀

**Comment by houking-can** [comment]
> 你好，我在跑这个代码的时候遇到了一个问题，报错为 ImportError: cannot import name 'pad_sequences' from 'data' (P:\Anaconda3\lib\site-packages\data__init__.py) 是不是我的data版本问题呀

有完整报错吗？代码太久了，我不知道是从哪里报错的

**Comment by houking-can** [comment]
> 你好，我在跑这个代码的时候遇到了一个问题，报错为 ImportError: cannot import name 'pad_sequences' from 'data' (P:\Anaconda3\lib\site-packages\data__init__.py) 是不是我的data版本问题呀

这应该是Python比较常见的包导入问题，import ner.data.pad_sequences as pad_sequences可以试试，相对导入和绝对导入，如果用的pycharm，试着把这个 mark dictionary as Source Root。不行的话可以上网查一下。实在不行把data.py移动到main.py同一级目录。

**Comment by ZiqiChing** [comment]
你好，刚刚去吃午饭了，完整的报错是这样的
Traceback (most recent call last):
  File "D:/Course/qwe-master/main.py", line 10, in <module>
    from ner.model import BiLSTM_CRF
  File "D:\Course\qwe-master\ner\model.py", line 9, in <module>
    from data import pad_sequences,batch_yield
ImportError: cannot import name 'pad_sequences' from 'data' (P:\Anaconda3\lib\site-packages\data\__init__.py)

**Comment by ZiqiChing** [comment]
谢谢大佬 果然是路径问题 第一次跑项目好多报错  可以问一下你是用什么跑的嘛 pycharm这个路径要改的话好麻烦

**Comment by houking-can** [comment]
以前用的pycharm跑，应该是没啥问题的，你可以查一下绝对import和相对import，好像可以写个 `__init__.py` ``放ner目录下。或者暴力点，把所有.py放同一个目录，基本能解决大部分import的问题。还有种方法， `sys.path.append(['./','./ner'])` 不一定是这么写，但是这个意思，你可以查一下
